### ISSUE TITLE
Handle case when tuition costs are missing

### ISSUE THREAD

**Issue by mwcraig** [mwcraig/headcounts-web#16]
This results in an error when I try stacking tables because the empty column is assumed to be `int64` while the rest of the cost data is `str` (because of the dollar sign).

```python_traceback
python updata_data_table.py /Users/mcraig/Dropbox/MSUM/headcounts/results-2018-04-19T15-27-56/all_enrollments.csv
Traceback (most recent call last):
  File "/Users/mcraig/conda-main/envs/heads_web3/lib/python3.6/site-packages/astropy/table/operations.py", line 839, in _vstack
    out[out_name] = col_cls.info.new_like(cols, n_rows, metadata_conflicts, out_name)
  File "/Users/mcraig/conda-main/envs/heads_web3/lib/python3.6/site-packages/astropy/table/column.py", line 173, in new_like
    ('meta', 'unit', 'format', 'description'))
  File "/Users/mcraig/conda-main/envs/heads_web3/lib/python3.6/site-packages/astropy/utils/data_info.py", line 594, in merge_cols_attributes
    out['dtype'] = metadata.common_dtype(cols)
  File "/Users/mcraig/conda-main/envs/heads_web3/lib/python3.6/site-packages/astropy/utils/metadata.py", line 64, in common_dtype
    raise tme
astropy.utils.metadata.MergeConflictError: Arrays have incompatible types ['str288', 'int64']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "updata_data_table.py", line 72, in <module>
    print(main(args.new_data))
  File "updata_data_table.py", line 59, in main
    join_type='exact')
  File "/Users/mcraig/conda-main/envs/heads_web3/lib/python3.6/site-packages/astropy/table/operations.py", line 281, in vstack
    out = _vstack(tables, join_type, col_name_map, metadata_conflicts)
  File "/Users/mcraig/conda-main/envs/heads_web3/lib/python3.6/site-packages/astropy/table/operations.py", line 844, in _vstack
    .format(out_name, err._incompat_types))
astropy.table.np_utils.TableMergeError: The 'Tuition -resident' columns have incompatible types: ['str288', 'int64']
```

**Comment by mwcraig** [comment]
Fixed at some point...
